In [1]:
import numpy as np 


def triangulariza(a,b,n):
    for k in range(n-1):
        for i in range(k+1,n):
            if a[i,k] == 0:
                print("A iteração ", k+1, " foi pulada")
                continue
            
            if a[i,k] == 0:
                print("Não Houve pulo da operação")
            
            m = a[i,k]/a[k,k]
            a[i,k] = 0
            
            for j in range(k+1,n):
                a[i,j] = a[i,j] - m*a[k,j]
            
            b[i,0] = b[i,0] - m*b[k,0]


A = np.matrix([[1,2,1],[0,1,-1],[3,-1,-2]])
B = np.matrix([[9],[3],[-4]])
triangulariza(A,B,3)
print("\n", A)
print("\n", B)

#Se o pivô for 0
def triangulariza2(a,b,n):
    for k in range(n-1):
        if a[k,k] == 0:
            break
        
        for i in range(k+1,n):
            if a[i,k] == 0:
                print("A iteração ", k+1, " foi pulada")
                continue
            
            if a[i,k] == 0:
                print("Não Houve pulo da operação")
            
            m = a[i,k]/a[k,k]
            a[i,k] = 0
            
            for j in range(k+1,n):
                a[i,j] = a[i,j] - m*a[k,j]
            
            b[i,0] = b[i,0] - m*b[k,0]


def triangulariza3(a,b,n):
    for i in range(n):
        if a[i,i] != 0: 
            continuar = 'verdadeiro'
        else:
            continuar = 'falso'
            break
    
    if continuar == 'true':
        triangulariza2(a,b,n)
    else:
        print("Determinante igual a 0")

    
E = np.matrix([[1,2,1],[2,0,-1],[3,-1,-2]])
F = np.matrix([[9],[3],[-4]])

triangulariza3(E,F,3)

print("\n", E)
print("\n", F)


C = np.matrix([[0,2,1],[2,1,-1],[3,-1,-2]])
D = np.matrix([[9],[3],[-4]])

triangulariza2(C,D,3)
print("\n", C)
print("\n", D)

#pivoteamento parcial
x=np.array([[1,2,1,9],[2,1,-1,3], [3,-1,-2,-4]],dtype='double')
print("\n\n",x)

#troca linhas
aux=np.copy(x[1,:])
x[1,:]=np.copy(x[0,:])
x[0,:]=np.copy(aux)
print("\n\n",x)

#zera X[1,0] e X[2,0]
x[1,:] = x[1,:] - (x[1,0]/x[0,0])*x[0,:]  
x[2,:] = x[2,:] - (x[2,0]/x[0,0])*x[0,:]  
print("\n\n",x)

#zera x[2,1]  
x[2,:] = x[2,:] - (x[2,1]/x[1,1])*x[1,:]  
print("\n\n",x)  


 
 
a = np.zeros(3)  
a[2] = x[2,3]/x[2,2];  
a[1] = (x[1,3] - x[1,2]*a[2])/x[1,1];  
a[0] = (x[0,3] - x[0,2]*a[2] - x[0,1]*a[1])/x[0,0] 
print("\n\n",a)



 [[ 1  2  1]
 [ 2  1 -1]
 [ 2 -1  2]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]



[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]



[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]



Ly = b.
 y = 
 [[ 1.]
 [ 2.]
 [ 3.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]



[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]



[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]




Ux = y.
 x = 
 [[-3.66666667]
 [ 7.5       ]
 [-0.75      ]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]



(array([[ 1.        ,  0.        ,  0.        ],
       [ 2.        ,  1.        ,  0.        ],
       [ 2.        ,  1.66666667,  1.        ]]), array([[ 1,  2,  1],
       [ 0, -3, -3],
       [ 0,  0,  5]]), matrix([[ 9],
        [ 3],
        [-4]]))


NameError: name 'solucao' is not defined